FROM heroku/heroku:18-build

ARG pack_uid=1000
ARG pack_gid=1000
ENV CNB_USER_ID=${pack_uid}
ENV CNB_GROUP_ID=${pack_gid}

RUN groupadd heroku --gid ${pack_gid} && \
    useradd heroku -u ${pack_uid} -g ${pack_gid} -md /app -s /bin/bash

ENV STACK "heroku-18"
ENV CNB_STACK_ID "heroku-18"

LABEL io.buildpacks.stack.id="heroku-18"

USER heroku
