description = "Ubuntu 26.04 AMD64+ARM64 base image with buildpacks for .NET, Go, Java, Node.js, PHP, Python, Ruby & Scala."

[stack]
id = "heroku-26"
build-image = "docker.io/heroku/heroku:26-build"
run-image = "docker.io/heroku/heroku:26"
run-image-mirrors = ["public.ecr.aws/heroku/heroku:26"]

[lifecycle]
version = "0.21.14"

[build]
image = "docker.io/heroku/heroku:26-build"

[run]
[[run.images]]
image = "docker.io/heroku/heroku:26"
mirrors = ["public.ecr.aws/heroku/heroku:26"]

[[buildpacks]]
  id = "heroku/deb-packages"
  uri = "docker://docker.io/heroku/buildpack-deb-packages@sha256:bb50e5973fbd84171d25423f178fff86f6e088743759c15011c0ad391e48e8d7"

[[buildpacks]]
  id = "heroku/dotnet"
  uri = "docker://docker.io/heroku/buildpack-dotnet@sha256:5af081d769475ee02761beb79ad5b8e9ba3fabcdd8aeceaa8a8843ff703075a8"

[[buildpacks]]
  id = "heroku/go"
  uri = "docker://docker.io/heroku/buildpack-go@sha256:fcd63e993c019d4b50b5c1457448720b68345b7b5e5b4f0a0834e4238f84385c"

[[buildpacks]]
  id = "heroku/java"
  uri = "docker://docker.io/heroku/buildpack-java@sha256:0bab59ceb9b97c3b55584e3f975553ad9e295a1187464b760b68ec2dc1acbcc2"

[[buildpacks]]
  id = "heroku/nodejs"
  uri = "docker://docker.io/heroku/buildpack-nodejs@sha256:bfb23fdaf294baa8334603e1892b3e70d025546a5501aa5cae6c1b97d2069fb6"

[[buildpacks]]
  id = "heroku/php"
  uri = "docker://docker.io/heroku/buildpack-php@sha256:8ad243ec217bd43e3f78a418e63ff79ea13d8eab75dd53831e0adaf0241a6592"

[[buildpacks]]
  id = "heroku/procfile"
  uri = "docker://docker.io/heroku/buildpack-procfile@sha256:f67a6be0cea63747736584b79209c59f9ec1170e15c67e0b4c192e500e2ecf48"

[[buildpacks]]
  id = "heroku/python"
  uri = "docker://docker.io/heroku/buildpack-python@sha256:a3edaea54e99f0e4eb6770a5b0894cc16bf6f2f8185f5f80370ff2cc818d8f9d"

[[buildpacks]]
  id = "heroku/ruby"
  uri = "docker://docker.io/heroku/buildpack-ruby@sha256:293bc549160aa78d8a354a756d594b5ef4f59f30c3bc9392f2f9bf502295ad70"

[[buildpacks]]
  id = "heroku/scala"
  uri = "docker://docker.io/heroku/buildpack-scala@sha256:2b6420592c77f6e8f5e968a8ebbe212fc302779937c70fa04a68bf3a6d7a71f9"

[[order]]
  [[order.group]]
    id = "heroku/deb-packages"
    version = "1.0.1"
    optional = true
  [[order.group]]
    id = "heroku/python"
    version = "6.5.6"
  [[order.group]]
    id = "heroku/procfile"
    version = "4.2.3"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/deb-packages"
    version = "1.0.1"
    optional = true
  [[order.group]]
    id = "heroku/nodejs"
    version = "5.7.13"
    optional = true
  [[order.group]]
    id = "heroku/jvm"
    version = "7.0.13"
    optional = true
  [[order.group]]
    id = "heroku/ruby"
    version = "12.4.1"
  [[order.group]]
    id = "heroku/procfile"
    version = "4.2.3"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/deb-packages"
    version = "1.0.1"
    optional = true
  [[order.group]]
    id = "heroku/java"
    version = "7.0.13"
  [[order.group]]
    id = "heroku/procfile"
    version = "4.2.3"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/deb-packages"
    version = "1.0.1"
    optional = true
  [[order.group]]
    id = "heroku/scala"
    version = "7.0.13"
  [[order.group]]
    id = "heroku/procfile"
    version = "4.2.3"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/deb-packages"
    version = "1.0.1"
    optional = true
  [[order.group]]
    id = "heroku/go"
    version = "4.0.0"
  [[order.group]]
    id = "heroku/procfile"
    version = "4.2.3"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/deb-packages"
    version = "1.0.1"
    optional = true
  [[order.group]]
    id = "heroku/php"
    version = "1.6.7"
  [[order.group]]
    id = "heroku/procfile"
    version = "4.2.3"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/deb-packages"
    version = "1.0.1"
    optional = true
  [[order.group]]
    id = "heroku/dotnet"
    version = "1.0.15"
  [[order.group]]
    id = "heroku/procfile"
    version = "4.2.3"
    optional = true

# this group is intentionally at the end, because projects in other languages often have e.g. a package.json
[[order]]
  [[order.group]]
    id = "heroku/deb-packages"
    version = "1.0.1"
    optional = true
  [[order.group]]
    id = "heroku/nodejs"
    version = "5.7.13"
  [[order.group]]
    id = "heroku/procfile"
    version = "4.2.3"
    optional = true
