description = "Ubuntu 26.04 AMD64+ARM64 base image with buildpacks for .NET, Go, Java, Node.js, PHP, Python, Ruby, Scala, & front-end websites."

[stack]
id = "heroku-26"
build-image = "docker.io/heroku/heroku:26-build"
run-image = "docker.io/heroku/heroku:26"
run-image-mirrors = ["public.ecr.aws/heroku/heroku:26"]

[lifecycle]
version = "0.21.17"

[build]
image = "docker.io/heroku/heroku:26-build"

[run]
[[run.images]]
image = "docker.io/heroku/heroku:26"
mirrors = ["public.ecr.aws/heroku/heroku:26"]

[[buildpacks]]
  id = "heroku/deb-packages"
  uri = "docker://docker.io/heroku/buildpack-deb-packages@sha256:bb50e5973fbd84171d25423f178fff86f6e088743759c15011c0ad391e48e8d7"

[[buildpacks]]
  id = "heroku/dotnet"
  uri = "docker://docker.io/heroku/buildpack-dotnet@sha256:5af081d769475ee02761beb79ad5b8e9ba3fabcdd8aeceaa8a8843ff703075a8"

[[buildpacks]]
  id = "heroku/go"
  uri = "docker://docker.io/heroku/buildpack-go@sha256:75de2761bcd09de6eb1ec9cfededd8ca6509c234e59d45f4e1b9921694986960"

[[buildpacks]]
  id = "heroku/java"
  uri = "docker://docker.io/heroku/buildpack-java@sha256:a842dddd9928e96c17585036de202b688824486a48d96690e00d93ca2816813d"

[[buildpacks]]
  id = "heroku/nodejs"
  uri = "docker://docker.io/heroku/buildpack-nodejs@sha256:75557fae896103779e10ddf1a94329247a446f23c261c00251f36bb9cdf62643"

[[buildpacks]]
  id = "heroku/php"
  uri = "docker://docker.io/heroku/buildpack-php@sha256:8ad243ec217bd43e3f78a418e63ff79ea13d8eab75dd53831e0adaf0241a6592"

[[buildpacks]]
  id = "heroku/procfile"
  uri = "docker://docker.io/heroku/buildpack-procfile@sha256:f67a6be0cea63747736584b79209c59f9ec1170e15c67e0b4c192e500e2ecf48"

[[buildpacks]]
  id = "heroku/python"
  uri = "docker://docker.io/heroku/buildpack-python@sha256:c0f418bce22e7563f0f0c03e1a79a38ba8883f85ce7210b746c4f25b15dbe664"

[[buildpacks]]
  id = "heroku/ruby"
  uri = "docker://docker.io/heroku/buildpack-ruby@sha256:293bc549160aa78d8a354a756d594b5ef4f59f30c3bc9392f2f9bf502295ad70"

[[buildpacks]]
  id = "heroku/scala"
  uri = "docker://docker.io/heroku/buildpack-scala@sha256:34f58db8de17f8745bffb66ef8f35d89fc379a2a6fdb116ee06dc0443e28ef3a"

[[buildpacks]]
  id = "heroku/static-web-server"
  uri = "docker://docker.io/heroku/buildpack-static-web-server@sha256:ce6e139ad251da2ab430f0aff405e3d27a3ec052f417827306bfbd5685976dee"

[[buildpacks]]
  id = "heroku/website-ember"
  uri = "docker://docker.io/heroku/buildpack-website-ember@sha256:90e1ffb7a92be5f4773f00f2a19ac8cb4166de490d3ce2ac1e48edcbf89bd274"

[[buildpacks]]
  id = "heroku/website-cra"
  uri = "docker://docker.io/heroku/buildpack-website-cra@sha256:c55e4a0c20ad74a2b51f7d4ee1f68b1c5b3d28c2ee354f938fece56545569d42"

[[buildpacks]]
  id = "heroku/website-nextjs"
  uri = "docker://docker.io/heroku/buildpack-website-nextjs@sha256:e957f12f3ee15ba9e3275f111d3131ab62b9b6a8b1b4daea575c77eda412f304"

[[buildpacks]]
  id = "heroku/website-public-html"
  uri = "docker://docker.io/heroku/buildpack-website-public-html@sha256:326d43a02025d47f9208d02537cf18b283af611851d25ee61059d52be215ccd1"

[[order]]
  [[order.group]]
    id = "heroku/deb-packages"
    version = "1.0.1"
    optional = true
  [[order.group]]
    id = "heroku/python"
    version = "6.6.0"
  [[order.group]]
    id = "heroku/procfile"
    version = "4.2.3"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/deb-packages"
    version = "1.0.1"
    optional = true
  [[order.group]]
    id = "heroku/nodejs"
    version = "5.7.15"
    optional = true
  [[order.group]]
    id = "heroku/jvm"
    version = "7.0.14"
    optional = true
  [[order.group]]
    id = "heroku/ruby"
    version = "12.4.1"
  [[order.group]]
    id = "heroku/procfile"
    version = "4.2.3"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/deb-packages"
    version = "1.0.1"
    optional = true
  [[order.group]]
    id = "heroku/java"
    version = "7.0.14"
  [[order.group]]
    id = "heroku/procfile"
    version = "4.2.3"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/deb-packages"
    version = "1.0.1"
    optional = true
  [[order.group]]
    id = "heroku/scala"
    version = "7.0.14"
  [[order.group]]
    id = "heroku/procfile"
    version = "4.2.3"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/deb-packages"
    version = "1.0.1"
    optional = true
  [[order.group]]
    id = "heroku/go"
    version = "4.0.2"
  [[order.group]]
    id = "heroku/procfile"
    version = "4.2.3"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/deb-packages"
    version = "1.0.1"
    optional = true
  [[order.group]]
    id = "heroku/php"
    version = "1.6.7"
  [[order.group]]
    id = "heroku/procfile"
    version = "4.2.3"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/deb-packages"
    version = "1.0.1"
    optional = true
  [[order.group]]
    id = "heroku/dotnet"
    version = "1.0.15"
  [[order.group]]
    id = "heroku/procfile"
    version = "4.2.3"
    optional = true

# For Node-based web frameworks & static site generators,
# the Front-end Web buildpacks parse package.json to detect specific dependencies.
# These groups are intentionally near the end, because projects in other languages often have a package.json.
[[order]]
  [[order.group]]
    id = "heroku/deb-packages"
    version = "1.0.1"
    optional = true
  [[order.group]]
    id = "heroku/nodejs"
    version = "5.7.15"
  [[order.group]]
    id = "heroku/static-web-server"
    version = "3.5.0"
  [[order.group]]
    id = "heroku/website-ember"
    version = "3.5.0"
  [[order.group]]
    id = "heroku/procfile"
    version = "4.2.3"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/deb-packages"
    version = "1.0.1"
    optional = true
  [[order.group]]
    id = "heroku/nodejs"
    version = "5.7.15"
  [[order.group]]
    id = "heroku/static-web-server"
    version = "3.5.0"
  [[order.group]]
    id = "heroku/website-nextjs"
    version = "3.5.0"
  [[order.group]]
    id = "heroku/procfile"
    version = "4.2.3"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/deb-packages"
    version = "1.0.1"
    optional = true
  [[order.group]]
    id = "heroku/nodejs"
    version = "5.7.15"
  [[order.group]]
    id = "heroku/static-web-server"
    version = "3.5.0"
  [[order.group]]
    id = "heroku/website-cra"
    version = "3.5.0"
  [[order.group]]
    id = "heroku/procfile"
    version = "4.2.3"
    optional = true

# This group is intentionally near the end, after the specific package.json dependency detection for Front-end Web buildpacks.
[[order]]
  [[order.group]]
    id = "heroku/deb-packages"
    version = "1.0.1"
    optional = true
  [[order.group]]
    id = "heroku/nodejs"
    version = "5.7.15"
  [[order.group]]
    id = "heroku/procfile"
    version = "4.2.3"
    optional = true

# For no-framework static websites, the Front-end Web buildpack detects public/index.html.
# This group is intentionally last because projects in other languages may include public HTML files.
[[order]]
  [[order.group]]
    id = "heroku/deb-packages"
    version = "1.0.1"
    optional = true
  [[order.group]]
    id = "heroku/static-web-server"
    version = "3.5.0"
  [[order.group]]
    id = "heroku/website-public-html"
    version = "3.5.0"
  [[order.group]]
    id = "heroku/procfile"
    version = "4.2.3"
    optional = true
