description = "Ubuntu 22.04 AMD64 base image with buildpacks for .NET, Go, Java, Node.js, PHP, Python, Ruby & Scala."

[stack]
id = "heroku-22"
build-image = "docker.io/heroku/heroku:22-cnb-build"
run-image = "docker.io/heroku/heroku:22-cnb"
run-image-mirrors = ["public.ecr.aws/heroku/heroku:22-cnb"]

[build]
image = "docker.io/heroku/heroku:22-cnb-build"

[run]
[[run.images]]
image = "docker.io/heroku/heroku:22-cnb"
mirrors = ["public.ecr.aws/heroku/heroku:22-cnb"]

[lifecycle]
version = "0.21.6"

[[buildpacks]]
  id = "heroku/deb-packages"
  uri = "docker://docker.io/heroku/buildpack-deb-packages@sha256:39167ecaee643641421d632b35998add6dc8ac08f49a39fc0f1063ad317fad82"

[[buildpacks]]
  id = "heroku/dotnet"
  uri = "docker://docker.io/heroku/buildpack-dotnet@sha256:3bdf5cd87fd552f7a1e55312340daa43f94b3b107de30d755161dcca9a787d17"

[[buildpacks]]
  id = "heroku/go"
  uri = "docker://docker.io/heroku/buildpack-go@sha256:47b1a4553b954f232377c6d13b2b062c5cdc542962ad361a0f32cbec30016679"

[[buildpacks]]
  id = "heroku/java"
  uri = "docker://docker.io/heroku/buildpack-java@sha256:ae7e93b0517c20188d2fc61de4c97a3dc5812507424ae4c41e5b17e1b5035c2c"

[[buildpacks]]
  id = "heroku/nodejs"
  uri = "docker://docker.io/heroku/buildpack-nodejs@sha256:896e66e864312bfddb8a2d34db3cb16fd45446b36b3cb0be0ca8f4f6d4120cb1"

[[buildpacks]]
  id = "heroku/php"
  uri = "docker://docker.io/heroku/buildpack-php@sha256:108491cd0b3140f3298402591a63389c4278398d13772f15b3a2a3ce78a636af"

[[buildpacks]]
  id = "heroku/procfile"
  uri = "docker://docker.io/heroku/buildpack-procfile@sha256:6ace71a217485b2932c8e4a311a502b68fde1a3c81e23576e29a9a1dba9a489a"

[[buildpacks]]
  id = "heroku/python"
  uri = "docker://docker.io/heroku/buildpack-python@sha256:9c215a42ab121edc46cf1bf911a65c7fd84e735d84b6cd18f9a2668f60e1924a"

[[buildpacks]]
  id = "heroku/ruby"
  uri = "docker://docker.io/heroku/buildpack-ruby@sha256:e9cd782ecef23303f3ad8b73723ba1a53a0b83c67c4a835f94cf14ed330678c6"

[[buildpacks]]
  id = "heroku/scala"
  uri = "docker://docker.io/heroku/buildpack-scala@sha256:a36e49a1bf9f8fa14d0e2fc87793213a840dbd5b8ea183b89b0e39ec91f35980"

[[order]]
  [[order.group]]
    id = "heroku/deb-packages"
    version = "0.3.0"
    optional = true
  [[order.group]]
    id = "heroku/python"
    version = "6.1.0"
  [[order.group]]
    id = "heroku/procfile"
    version = "4.2.1"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/deb-packages"
    version = "0.3.0"
    optional = true
  [[order.group]]
    id = "heroku/nodejs"
    version = "5.5.5"
    optional = true
  [[order.group]]
    id = "heroku/jvm"
    version = "7.0.10"
    optional = true
  [[order.group]]
    id = "heroku/ruby"
    version = "12.3.0"
  [[order.group]]
    id = "heroku/procfile"
    version = "4.2.1"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/deb-packages"
    version = "0.3.0"
    optional = true
  [[order.group]]
    id = "heroku/java"
    version = "7.0.10"
  [[order.group]]
    id = "heroku/procfile"
    version = "4.2.1"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/deb-packages"
    version = "0.3.0"
    optional = true
  [[order.group]]
    id = "heroku/scala"
    version = "7.0.10"
  [[order.group]]
    id = "heroku/procfile"
    version = "4.2.1"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/deb-packages"
    version = "0.3.0"
    optional = true
  [[order.group]]
    id = "heroku/go"
    version = "2.2.1"
  [[order.group]]
    id = "heroku/procfile"
    version = "4.2.1"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/deb-packages"
    version = "0.3.0"
    optional = true
  [[order.group]]
    id = "heroku/php"
    version = "1.5.1"
  [[order.group]]
    id = "heroku/procfile"
    version = "4.2.1"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/deb-packages"
    version = "0.3.0"
    optional = true
  [[order.group]]
    id = "heroku/dotnet"
    version = "1.0.5"
  [[order.group]]
    id = "heroku/procfile"
    version = "4.2.1"
    optional = true

# this group is intentionally at the end, because projects in other languages often have e.g. a package.json
[[order]]
  [[order.group]]
    id = "heroku/deb-packages"
    version = "0.3.0"
    optional = true
  [[order.group]]
    id = "heroku/nodejs"
    version = "5.5.5"
  [[order.group]]
    id = "heroku/procfile"
    version = "4.2.1"
    optional = true
