description = "[DEPRECATED] Ubuntu 22.04 AMD64 base image with buildpacks for .NET, Go, Java, Node.js, PHP, Python, Ruby & Scala."

[stack]
id = "heroku-22"
build-image = "docker.io/heroku/heroku:22-cnb-build"
run-image = "docker.io/heroku/heroku:22-cnb"
run-image-mirrors = ["public.ecr.aws/heroku/heroku:22-cnb"]

[build]
image = "docker.io/heroku/heroku:22-cnb-build"

[run]
[[run.images]]
image = "docker.io/heroku/heroku:22-cnb"
mirrors = ["public.ecr.aws/heroku/heroku:22-cnb"]

[lifecycle]
version = "0.21.9"

[[buildpacks]]
  id = "heroku/eol-warning"
  uri = "./eol-buildpack/"

[[buildpacks]]
  id = "heroku/deb-packages"
  uri = "docker://docker.io/heroku/buildpack-deb-packages@sha256:282783174259d1559e1f2e068d2db46281557c3cc71eba4f76b6b1bf1ae7dd4e"

[[buildpacks]]
  id = "heroku/dotnet"
  uri = "docker://docker.io/heroku/buildpack-dotnet@sha256:1b037400f597d7f81149130f27b0246cc316de8358e7d3a8f743233a0d709fc2"

[[buildpacks]]
  id = "heroku/go"
  uri = "docker://docker.io/heroku/buildpack-go@sha256:be3828c4c216a84619d8a220e4b59ed26a04f859a773e8593bab4267ebc5749a"

[[buildpacks]]
  id = "heroku/java"
  uri = "docker://docker.io/heroku/buildpack-java@sha256:ffcec832e829f935031a23103b7cdf30072e98dfe720afc66aea700eeeb2101f"

[[buildpacks]]
  id = "heroku/nodejs"
  uri = "docker://docker.io/heroku/buildpack-nodejs@sha256:c7dc847b19aa1106ae2d5e1b9fa693c61d1dd3e76685167fa076164ab6c396da"

[[buildpacks]]
  id = "heroku/php"
  uri = "docker://docker.io/heroku/buildpack-php@sha256:20b6dd2ed48942593465081653ae47200a82e431838fcfff1a91ba9b90adfe66"

[[buildpacks]]
  id = "heroku/procfile"
  uri = "docker://docker.io/heroku/buildpack-procfile@sha256:df5cf3fe9e25ac7956d3d4b77844e4d23fc182ef0de49599c2ec4e3b17316448"

[[buildpacks]]
  id = "heroku/python"
  uri = "docker://docker.io/heroku/buildpack-python@sha256:9786430c96b47d2e47b9e3e279bf3f3f34c83ef263ff78d6a2be3f5f173e5d7b"

[[buildpacks]]
  id = "heroku/ruby"
  uri = "docker://docker.io/heroku/buildpack-ruby@sha256:833a53a0bee713c27898d9d365505a711128f1cd0d943c1d6c9459c9e9fa2505"

[[buildpacks]]
  id = "heroku/scala"
  uri = "docker://docker.io/heroku/buildpack-scala@sha256:fb39a0f96cd3b7c7c470f02240843eaf4931405c7651062088923136065a4beb"

[[order]]
  [[order.group]]
    id = "heroku/deb-packages"
    version = "1.0.0"
    optional = true
  [[order.group]]
    id = "heroku/python"
    version = "6.5.1"
  [[order.group]]
    id = "heroku/procfile"
    version = "4.2.2"
    optional = true
  [[order.group]]
    id = "heroku/eol-warning"
    version = "1.0.0"

[[order]]
  [[order.group]]
    id = "heroku/deb-packages"
    version = "1.0.0"
    optional = true
  [[order.group]]
    id = "heroku/nodejs"
    version = "5.7.3"
    optional = true
  [[order.group]]
    id = "heroku/jvm"
    version = "7.0.11"
    optional = true
  [[order.group]]
    id = "heroku/ruby"
    version = "12.4.0"
  [[order.group]]
    id = "heroku/procfile"
    version = "4.2.2"
    optional = true
  [[order.group]]
    id = "heroku/eol-warning"
    version = "1.0.0"

[[order]]
  [[order.group]]
    id = "heroku/deb-packages"
    version = "1.0.0"
    optional = true
  [[order.group]]
    id = "heroku/java"
    version = "7.0.11"
  [[order.group]]
    id = "heroku/procfile"
    version = "4.2.2"
    optional = true
  [[order.group]]
    id = "heroku/eol-warning"
    version = "1.0.0"

[[order]]
  [[order.group]]
    id = "heroku/deb-packages"
    version = "1.0.0"
    optional = true
  [[order.group]]
    id = "heroku/scala"
    version = "7.0.11"
  [[order.group]]
    id = "heroku/procfile"
    version = "4.2.2"
    optional = true
  [[order.group]]
    id = "heroku/eol-warning"
    version = "1.0.0"

[[order]]
  [[order.group]]
    id = "heroku/deb-packages"
    version = "1.0.0"
    optional = true
  [[order.group]]
    id = "heroku/go"
    version = "2.2.3"
  [[order.group]]
    id = "heroku/procfile"
    version = "4.2.2"
    optional = true
  [[order.group]]
    id = "heroku/eol-warning"
    version = "1.0.0"

[[order]]
  [[order.group]]
    id = "heroku/deb-packages"
    version = "1.0.0"
    optional = true
  [[order.group]]
    id = "heroku/php"
    version = "1.6.1"
  [[order.group]]
    id = "heroku/procfile"
    version = "4.2.2"
    optional = true
  [[order.group]]
    id = "heroku/eol-warning"
    version = "1.0.0"

[[order]]
  [[order.group]]
    id = "heroku/deb-packages"
    version = "1.0.0"
    optional = true
  [[order.group]]
    id = "heroku/dotnet"
    version = "1.0.10"
  [[order.group]]
    id = "heroku/procfile"
    version = "4.2.2"
    optional = true
  [[order.group]]
    id = "heroku/eol-warning"
    version = "1.0.0"

# this group is intentionally at the end, because projects in other languages often have e.g. a package.json
[[order]]
  [[order.group]]
    id = "heroku/deb-packages"
    version = "1.0.0"
    optional = true
  [[order.group]]
    id = "heroku/nodejs"
    version = "5.7.3"
  [[order.group]]
    id = "heroku/procfile"
    version = "4.2.2"
    optional = true
  [[order.group]]
    id = "heroku/eol-warning"
    version = "1.0.0"
